#Config

### Data Generation
#glob path to sensor data, recursive wildcards allowed
rgb_sensor_pool: /orange/ewhite/NeonData/*/DP3.30010.001/**/Camera/**/*.tif 
HSI_sensor_pool: /orange/ewhite/NeonData/*/DP3.30006.001/**/Reflectance/*.h5
CHM_pool: /orange/ewhite/NeonData/**/CanopyHeightModelGtif/*.tif
HSI_tif_dir: /orange/idtrees-collab/Hyperspectral_tifs/

#NEON data filtering
min_stem_diameter: 10
#Minimum number of test samples per class to be included
min_train_samples: 10
min_test_samples: 4

#The proportion of plotIDs to use test
test_fraction: 0.1
#Iterations to search for the best train-test split that mantains the largest number of species. Set to 1 for debugging, no files will be written
iterations: 200
#minimum CHM height, leave blank to skip CHM filtering
min_CHM_height: 1
#Minimum difference between measured height and CHM height
min_CHM_diff: 3

#Megaplot XY Data
megaplot_dir: /orange/idtrees-collab/megaplot/

#Outlier detection
autoencoder_epochs: 15
outlier_threshold: 0.95

#Crop generation
convert_h5: True
#Directoy to store cropped images from crowns
crop_dir: /blue/ewhite/b.weinstein/DeepTreeAttention/year_crops/

#resized Pixel size of the crowns. Square crops around each pixel of size x are used
image_size: 11

#Network Parameters
gpus: 1
workers: 20
batch_size: 64
bands: 369
lr: 0.001
fast_dev_run: False
accelerator: dp
epochs: 55

#Evaluation config
#Top k class recall score
top_k: 4
#Number of individuals to plot in comet graphics tab
plot_n_individuals: 10

#Comet dashboard
comet_workspace: bw4sz
