#simulation config
batch_size: 8
workers: 1
novel_class_examples: 20
samples: 5000
proportion_switch: 0.001

#Comet dashboard
comet_workspace: bw4sz

#Training
gpus: 1
fast_dev_run: False
accelerator:
epochs: 50
lr: 0.01
classification_loss_scalar: 0.1

#Outlier detection
outlier_threshold: 0.95
