#simulation config
batch_size: 128
workers: 20
novel_class_examples: 20
proportion_switch: 0.1

#Comet dashboard
comet_workspace: bw4sz

#Training
gpus: 0
fast_dev_run: False
accelerator: dp
epochs: 50
lr: 0.001

#Outlier detection
outlier_threshold: 0.95
